name: Build and deploy Powershell project to Azure Function App - azurecostestimator-back

on: release

jobs:
  deploy-to-production:
    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master  
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: 'azurecostestimator-back'
        slot-name: 'production'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.publishprofile_test }}